[package]
name = "two-k-26-ball"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anchor-lang = "0.29"
anchor-spl = "0.29"
solana-program = "1.17"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
